version: '3.9'

services:
  backend:
    build: ./backend
    container_name: vote-backend
    ports:
      - "8001:8001"
    volumes:
      - vote-data:/data
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: vote-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  vote-data:
